@url = http://localhost:3000

###

PUT http://localhost:3000/pregunta/685765c4702e0b41be37c552
Content-Type: application/json

{
  "pregunta": "¿Cuál es la capital de España?",
  "opciones": ["Madrid", "Barcelona", "Sevilla", "Valencia"],
  "respuestaCorrecta": "Madrid"
}


###
GET http://localhost:3000/pregunta/traerbyId/685765c4702e0b41be37c552

###
GET http://localhost:3000/pregunta/traer

